---
# tasks file for nginx_install
- name: For Debian
  block:
       - name: install Nginx
         apt:
           state: latest
           name:  nginx 
           update_cache: yes
         tags:
           - nginx_install
           - nginx_deb
  when:  (ansible_facts['os_family'] == "Debian")


- name: For RedHat
  block:
      - name: add epel repo
        yum:
          state: present
          name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        tags:
          - epel_repo 
      - name: install Nginx
        yum:
          state: latest
          name:  nginx
          update_cache: yes          
        tags:
          - nginx_install
          - nginx_rh
  when:  (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
